# Generated by Django 2.1.7 on 2019-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
                ('right', models.CharField(choices=[(1, 'member'), (2, 'vip'), (3, 'svip')], default=1, max_length=6, verbose_name='会员等级')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
