# Generated by Django 2.1.7 on 2019-02-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='right',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'member'), (2, 'vip'), (3, 'svip')], default=1, max_length=6, verbose_name='会员等级'),
        ),
    ]
