# Generated by Django 2.1.7 on 2019-04-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='begin.Category', verbose_name='Api类目'),
        ),
    ]
