# Generated by Django 2.1.7 on 2019-04-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0002_api_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'verbose_name': '接口表', 'verbose_name_plural': '接口表'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': '环境信息表', 'verbose_name_plural': '环境信息表'},
        ),
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name': '全局变量表', 'verbose_name_plural': '全局变量表'},
        ),
    ]
