# Generated by Django 2.1.7 on 2019-04-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0003_auto_20190410_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.TextField(blank=True, default='', help_text='类别描述', null=True, verbose_name='类别描述'),
        ),
    ]
