# Generated by Django 2.1.7 on 2019-04-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0004_auto_20190410_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '接口分类树', 'verbose_name_plural': '接口分类树'},
        ),
    ]
