# Generated by Django 2.1.7 on 2019-04-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0005_auto_20190410_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='module',
            new_name='project',
        ),
    ]
