# Generated by Django 2.1.7 on 2019-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0006_auto_20190410_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='TODO',
        ),
        migrations.AlterField(
            model_name='case',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='配置信息'),
        ),
    ]
