# Generated by Django 2.1.7 on 2019-05-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0007_auto_20190410_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api', to='begin.Category', verbose_name='Api类目'),
        ),
    ]
