# Generated by Django 2.1.7 on 2019-06-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0008_auto_20190505_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='begin.Category', verbose_name='case类目'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='begin.Category', verbose_name='项目类目'),
        ),
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='api', to='begin.Category', verbose_name='Api类目'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='project',
        ),
        migrations.AddField(
            model_name='case',
            name='project',
            field=models.ManyToManyField(to='begin.Project'),
        ),
    ]
