# Generated by Django 2.1.7 on 2019-06-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0009_auto_20190607_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='config',
            new_name='step_info',
        ),
        migrations.AlterField(
            model_name='api',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='begin.Category', verbose_name='Api类目'),
        ),
    ]
