# Generated by Django 2.1.7 on 2019-06-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0011_auto_20190616_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='config',
        ),
    ]
