# Generated by Django 2.1.7 on 2019-07-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0014_auto_20190715_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='api',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='begin.API', verbose_name='Api'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='create_user',
            field=models.CharField(default='admin', max_length=32, verbose_name='创建人'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='is_run',
            field=models.IntegerField(choices=[(0, '不运行'), (1, '运行')], default=1, verbose_name='是否运行'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='update_user',
            field=models.CharField(default='admin', max_length=32, verbose_name='修改人'),
            preserve_default=False,
        ),
    ]
