# Generated by Django 2.1.7 on 2019-07-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0015_auto_20190721_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='header',
            field=models.TextField(default=1, max_length=200, verbose_name='请求头'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='protocol',
            field=models.CharField(default=1, max_length=10, verbose_name='请求协议'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='times',
            field=models.IntegerField(default=1, verbose_name='循环次数'),
        ),
        migrations.AlterField(
            model_name='case',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='begin.Project'),
        ),
        migrations.AlterField(
            model_name='step',
            name='extract',
            field=models.TextField(verbose_name='提取变量表达式'),
        ),
        migrations.AlterField(
            model_name='step',
            name='validate',
            field=models.TextField(max_length=256, verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='step',
            name='variables',
            field=models.TextField(verbose_name='变量'),
        ),
    ]
