# Generated by Django 2.1.7 on 2019-07-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0017_auto_20190723_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='body_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='请求体注释'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='api',
            name='header_remark',
            field=models.CharField(default=1, max_length=255, verbose_name='请求头注释'),
            preserve_default=False,
        ),
    ]
