# Generated by Django 2.1.7 on 2019-07-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0018_auto_20190724_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='response',
            field=models.TextField(default=1, max_length=255, verbose_name='接口返回'),
            preserve_default=False,
        ),
    ]
