# Generated by Django 2.1.7 on 2019-07-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0019_api_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='is_run',
            new_name='runFlag',
        ),
        migrations.AlterField(
            model_name='case',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
