# Generated by Django 2.1.7 on 2019-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0020_auto_20190727_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='create_user',
            field=models.CharField(auto_created=True, max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=128, verbose_name='用例名称'),
        ),
    ]
