# Generated by Django 2.1.7 on 2019-08-05 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0021_auto_20190728_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='header_remark',
            new_name='headers_remark',
        ),
    ]
