# Generated by Django 2.1.7 on 2019-08-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0022_auto_20190805_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='header',
            new_name='headers',
        ),
    ]
