# Generated by Django 2.1.7 on 2019-08-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0023_auto_20190805_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='body_remark',
            new_name='bodyRemark',
        ),
        migrations.RenameField(
            model_name='api',
            old_name='headers_remark',
            new_name='headersRemark',
        ),
        migrations.AddField(
            model_name='api',
            name='bodyType',
            field=models.CharField(default=1, max_length=5, verbose_name='主体类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='api',
            name='headers',
            field=models.TextField(verbose_name='请求头'),
        ),
        migrations.AlterField(
            model_name='api',
            name='response',
            field=models.TextField(verbose_name='接口返回'),
        ),
    ]
