# Generated by Django 2.1.7 on 2019-08-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0024_auto_20190807_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='extract',
            field=models.TextField(blank=True, verbose_name='提取变量表达式'),
        ),
        migrations.AlterField(
            model_name='step',
            name='validate',
            field=models.TextField(blank=True, max_length=256, verbose_name='断言'),
        ),
        migrations.AlterField(
            model_name='step',
            name='variables',
            field=models.TextField(blank=True, verbose_name='变量'),
        ),
    ]
