# Generated by Django 2.1.7 on 2019-08-10 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('begin', '0025_auto_20190810_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='bodyRemark',
        ),
        migrations.RemoveField(
            model_name='api',
            name='bodyType',
        ),
        migrations.RemoveField(
            model_name='api',
            name='headersRemark',
        ),
        migrations.AddField(
            model_name='step',
            name='body',
            field=models.TextField(default=1, verbose_name='请求参数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='bodyType',
            field=models.CharField(default=1, max_length=5, verbose_name='主体类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='headers',
            field=models.TextField(default=1, verbose_name='请求头'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='method',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='url',
            field=models.CharField(default=1, max_length=256, verbose_name='请求url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='begin.Category', verbose_name='case类目'),
        ),
        migrations.AlterField(
            model_name='step',
            name='validate',
            field=models.TextField(blank=True, verbose_name='断言'),
        ),
    ]
