# Generated by Django 2.1.7 on 2019-03-03 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='接口描述')),
                ('endpoint', models.CharField(max_length=256, verbose_name='接口地址')),
            ],
            options={
                'verbose_name': '接口信息表',
                'verbose_name_plural': '接口信息表',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用例名称')),
                ('version', models.CharField(max_length=32, verbose_name='模块版本')),
                ('description', models.CharField(max_length=256, verbose_name='用例描述')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例信息表',
                'verbose_name_plural': '用例信息表',
            },
        ),
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='步骤名称')),
                ('description', models.CharField(max_length=256, verbose_name='用例描述')),
                ('method', models.IntegerField(choices=[(1, 'post'), (2, 'get'), (3, 'put'), (4, 'delete')], verbose_name='请求方式')),
                ('header', models.CharField(max_length=256, verbose_name='请求头')),
                ('data', models.CharField(max_length=256, verbose_name='请求数据')),
                ('assert_response', models.CharField(max_length=256, verbose_name='期望')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='模块', to='runner.Case')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Api', verbose_name='接口地址')),
            ],
            options={
                'verbose_name': '步骤表',
                'verbose_name_plural': '步骤表',
            },
        ),
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('server', models.CharField(max_length=100, verbose_name='服务地址')),
                ('account', models.CharField(max_length=50, verbose_name='登录名')),
                ('password', models.CharField(max_length=50, verbose_name='登陆密码')),
                ('type', models.IntegerField(choices=[(1, 'Sql Server'), (2, 'MySQL'), (3, 'Oracle'), (4, 'Mongodb'), (5, 'InfluxDB')], default=2, verbose_name='数据库类型')),
                ('desc', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '数据库信息',
                'db_table': 'DataBase',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='模块名称')),
                ('developer', models.CharField(max_length=256, verbose_name='开发人员')),
                ('tester', models.CharField(max_length=256, verbose_name='测试人员')),
                ('status', models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], max_length=2, verbose_name='模块状态')),
                ('description', models.CharField(max_length=256, verbose_name='模块描述')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '模块信息表',
                'verbose_name_plural': '模块信息表',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名称')),
                ('developer', models.CharField(max_length=256, verbose_name='开发人员')),
                ('tester', models.CharField(max_length=256, verbose_name='测试人员')),
                ('status', models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], max_length=2, verbose_name='项目状态')),
                ('description', models.CharField(max_length=256, verbose_name='项目描述')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目信息表',
                'verbose_name_plural': '项目信息表',
            },
        ),
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Project')),
            ],
            options={
                'verbose_name': '全局变量',
                'db_table': 'Variables',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='项目', to='runner.Project'),
        ),
        migrations.AddField(
            model_name='case',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='模块', to='runner.Module'),
        ),
        migrations.AddField(
            model_name='api',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Module'),
        ),
    ]
