# Generated by Django 2.1.7 on 2019-03-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], verbose_name='模块状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], verbose_name='项目状态'),
        ),
    ]
