# Generated by Django 2.1.7 on 2019-03-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20190303_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
