# Generated by Django 2.1.7 on 2019-03-04 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20190303_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to='runner.Module'),
        ),
        migrations.AlterField(
            model_name='case',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='runner.Module'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step', to='runner.Case'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='runner.Project'),
        ),
        migrations.AlterField(
            model_name='module',
            name='status',
            field=models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], default=0, verbose_name='模块状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, '开发中'), (1, '已完毕')], default=0, verbose_name='项目状态'),
        ),
    ]
