# Generated by Django 2.1.7 on 2019-03-05 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0005_auto_20190304_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestep',
            name='endpoint',
        ),
        migrations.AddField(
            model_name='casestep',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='接口地址'),
            preserve_default=False,
        ),
    ]
