# Generated by Django 2.1.7 on 2019-03-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0006_auto_20190305_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('body', models.TextField(verbose_name='主体信息')),
                ('base_url', models.CharField(max_length=100, verbose_name='请求地址')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Project')),
            ],
            options={
                'verbose_name': '环境信息',
                'db_table': 'Config',
            },
        ),
    ]
