# Generated by Django 2.1.7 on 2019-03-07 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0007_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variables',
            options={'verbose_name': '全局变量', 'verbose_name_plural': '全局变量'},
        ),
    ]
