# Generated by Django 2.1.7 on 2019-03-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0010_auto_20190311_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debugtalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='# write you code', verbose_name='python代码')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='runner.Project')),
            ],
            options={
                'verbose_name': '驱动库',
                'db_table': 'Debugtalk',
            },
        ),
    ]
